[package]
name = "osxnotifysounds"
version = "0.1.0"
authors = ["Joseph Gimenez <joseph.gimenez@snagajob.com>"]

[dependencies]
rusqlite = "0.12.0"
serde_json = "1.0"
clap = "~2.19.0"
rayon = "0.7.1"


[features]
default = []